# Generated by Django 4.2.2 on 2023-07-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_zumalogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='capacity',
            new_name='quntity',
        ),
    ]
