# Generated by Django 4.2.2 on 2023-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_booking_hotel_room_hotel_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='quntity',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='room_images'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
