# Generated by Django 3.2.20 on 2023-07-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_bookedroom_total_price_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
